python3 parse_by_time.py --sender=3 --reciever=6 --accuracy=8 --pcap_file from3 & 
python3 parse_by_time.py --sender=6 --reciever=3 --accuracy=8 --pcap_file to3 & 
python3 parse_by_time.py --sender=4 --reciever=6 --accuracy=8 --pcap_file from4 & 
python3 parse_by_time.py --sender=6 --reciever=4 --accuracy=8 --pcap_file to4 & 
python3 parse_by_time.py --sender=3 --reciever=6 --accuracy=10 --pcap_file from3 & 
python3 parse_by_time.py --sender=6 --reciever=3 --accuracy=10 --pcap_file to3 & 
python3 parse_by_time.py --sender=4 --reciever=6 --accuracy=10 --pcap_file from4 & 
python3 parse_by_time.py --sender=6 --reciever=4 --accuracy=10 --pcap_file to4 & 
python3 parse_by_time.py --sender=3 --reciever=6 --accuracy=11 --pcap_file from3 & 
python3 parse_by_time.py --sender=6 --reciever=3 --accuracy=11 --pcap_file to3 & 
python3 parse_by_time.py --sender=4 --reciever=6 --accuracy=11 --pcap_file from4 & 
python3 parse_by_time.py --sender=6 --reciever=4 --accuracy=11 --pcap_file to4 & 
python3 parse_by_time.py --sender=3 --reciever=6 --accuracy=12 --pcap_file from3 & 
python3 parse_by_time.py --sender=6 --reciever=3 --accuracy=12 --pcap_file to3 & 
python3 parse_by_time.py --sender=4 --reciever=6 --accuracy=12 --pcap_file from4 & 
python3 parse_by_time.py --sender=6 --reciever=4 --accuracy=12 --pcap_file to4 & 
